#!/bin/bash

export $(grep -v '^#' .env | xargs)

if [ -n "$1" ] && [ -f "$1" ]; then
  psql -U $POSTGRES_USER -d $POSTGRES_DB -h localhost -p $POSTGRES_PORT -f "$1"
else
  psql -U $POSTGRES_USER -d $POSTGRES_DB -h localhost -p $POSTGRES_PORT
fi
